export const mallIndexUrl = '/api/index/{{mallCode}}'
export const goodsSerUrl='/api/mall/{{mallCode}}/goods'
export const storeLookUrl='/api/mall/{{mallCode}}/chosen/store'
export const favoriteUrl='/api/shop/user/favorite/store'
export const firstCodeUrl='/api/shop/category/sublist/first'
export const childCategoryCodeUrl='/api/shop/category/sublist/{{parentCategoryCode}}'
export const storeSerListUrl='/api/mall/{{mallCode}}/store'
export const floorStoreUrl='/api/floor/threelevellist/{{mallCode}}'
export const addressListUrl = '/api/user/usershopaddress/list'
export const addressDeleteUrl = '/api/user/usershopaddress/{{id}}'
export const removeDefaultUrl = '/admin/user/usershopaddress/user/usershopaddress/cancel/{{id}}'
export const addressInfoUrl = '/api/user/usershopaddress/info/{{id}}'
export const addressDefaultUrl = '/api/user/usershopaddress/default/{{id}}'
export const saveAddressUrl = '/api/user/usershopaddress/save'
export const editAddressUrl = '/api/user/usershopaddress/update'
export const newsUrl='/api/mall/{{mallCode}}/store/news'
export const workIndexUrl ='/admin/mall/store/index'
export const superAdminWorkUrl='/admin/mall/store/{{mallCode}}/index'
export const isAdminUrl='/api/mall/user/relation/{{mallCode}}'
export const identityUserUrl ='/api/user/byuserid'
export const adminMallStoreListUrl = "/admin/mall/store/super/storelist"
export const purchaserStoreUrl = '/api/user/purchaser/store'
export const resetPasswordUrl = "/api/user/resetpassword"
export const phoneMessageUrl = "/oauth/code/sms"
export const registerUrl = "/api/user/register"
export const registerPhoneMsgUrl = "/api/smsCode"
export const userFloorInfoUrl = "/admin/floor/malluser/userfloor/login"
export const changeIconUrl = "/api/user/headpic"